openapi: 3.0.0
info:
  title: Pack Calculator API
  description: API for managing pack configurations and calculating optimal pack combinations
  version: 1.0.0

servers:
  - url: /api
    description: Base API path

components:
  schemas:
    PackConfiguration:
      type: object
      properties:
        packSizes:
          type: array
          items:
            type: integer
          description: Array of available pack sizes
          example: [250, 500, 1000, 2000, 5000]

    CalculateRequest:
      type: object
      required:
        - orderQuantity
      properties:
        orderQuantity:
          type: integer
          description: The quantity of items to be packed
          example: 1001
          minimum: 1

    CalculateResponse:
      type: object
      properties:
        orderQuantity:
          type: integer
          description: The original order quantity
          example: 1001
        totalItems:
          type: integer
          description: Total number of items in all packs
          example: 1002
        totalPacks:
          type: integer
          description: Total number of packs used
          example: 3
        pack_configurations:
          type: array
          items:
            type: object
            properties:
              size:
                type: integer
                description: Size of the pack
                example: 500
              quantity:
                type: integer
                description: Number of packs of this size
                example: 2
        success:
          type: boolean
          description: Whether the calculation was successful
          example: true
        errorMessage:
          type: string
          description: Error message in case of failure
          example: ""

    Error:
      type: object
      properties:
        Type:
          type: string
          example: "INTERNAL_ERROR"
        Message:
          type: string
          example: "An error occurred while processing the request"
        Err:
          type: object
          description: Additional error details

  responses:
    TooManyRequests:
      description: Rate limit exceeded
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    InternalError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
            
  securitySchemes:
    RateLimit:
      type: apiKey
      name: X-Rate-Limit
      in: header
      description: Rate limiting is applied to all API endpoints

paths:
  /packs:
    get:
      summary: Get active pack configuration
      description: Returns the currently active pack sizes configuration
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PackConfiguration'
        '500':
          $ref: '#/components/responses/InternalError'
        '429':
          $ref: '#/components/responses/TooManyRequests'

    post:
      summary: Create new pack configuration
      description: Creates a new pack configuration and sets it as active
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PackConfiguration'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PackConfiguration'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          $ref: '#/components/responses/InternalError'
        '429':
          $ref: '#/components/responses/TooManyRequests'

  /calculate:
    post:
      summary: Calculate optimal pack combination
      description: Calculates the optimal combination of packs for a given order quantity
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CalculateRequest'
      responses:
        '200':
          description: Successful calculation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CalculateResponse'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          $ref: '#/components/responses/InternalError'
        '429':
          $ref: '#/components/responses/TooManyRequests'

security:
  - RateLimit: []